### ISSUE TITLE
Please consider dropping Underscore dependency

### ISSUE THREAD

**Issue by jacksonrayhamilton** [duereg/normalize-object#1]
The file size of a library can be a pressing matter for web developers. I'd like to use this library, but I'd rather not pull in all of Underscore in the process. (In my project, I use Lodash.) Thankfully, this library doesn't appear to rely too heavily on Underscore, as I only see the `isArray` and `isObject` methods used. You could potentially save your users ~5kb by replacing those methods with the following implementations:

``` coffee
isArray = Array.isArray or (val) -> Object.prototype.toString.call(val) is '[object Array]'
isObject = (val) -> val isnt null and typeof val is 'object'
```

Would you be willing to remove Underscore to reduce the file size of this library?

**Comment by duereg** [comment]
removed in 1.3.0
