### ISSUE TITLE
Last version broke npm install

### ISSUE THREAD

**Issue by rjunior-admatic** [duereg/normalize-object#4]
Hello @duereg 

On the last version you added a postinstall script on package.json to build the coffee script.

https://github.com/duereg/normalize-object/blob/90937b26c7414537c88517e2078517a0c17ab289/package.json#L28-L32

It breaks production builds, because gulp is a dev dependency, not a production one:

https://github.com/duereg/normalize-object/blob/90937b26c7414537c88517e2078517a0c17ab289/package.json#L38-L47

Ideally you should publish the built code, as it was on 1.1.5.

This is a major issue, as this library has almost 2k weekly downloads from npm.

For now we updated all projects to use the 1.1.5 version, that still works.

**Comment by duereg** [comment]
ah whoops. Let me see what I can do

**Comment by rjunior-admatic** [comment]
wow thanks for the lightning flash reply.

**Comment by duereg** [comment]
@rjunior-admatic published 1.2.3. Let me know if that works for you. 

I've been updating my OSS the last couple of days; you just got lucky

**Comment by rjunior-admatic** [comment]
Works like a charm. Thanks!

**Comment by duereg** [comment]
Glad to help. About to release 2.0 in a minute if you're interested.
